### ISSUE TITLE
GenProp0039 - HMM-CLUST

### ISSUE THREAD

**Issue by LornaMGnify** [ebi-pf-team/genome-properties#10]
The final step in GenProp0039 is an HMM-CLUST - do we calculate this atm?
From the release notes: The method "HMM-CLUST" allows an overly broad HMM to identify proteins likely to belong to a system when they co-cluster (within 3000 bp) with other proteins from the same GenomeProperty that were identified by the method "HMM".
I have added the IPR for the PFAM given as evidence for this HMM-CLUST step - but it is a domain rather than a family. This domain DOES match to non-mammals.

**Comment by happy-lorna** [comment]
Do you think I can change the RQ state (and hence TH level) for the final step given that it hits non-mammals? Or leave property as is, due to fact that we do not know for sure WHICH transaminase is used in non-mammals?

**Comment by rdfinn** [comment]
Okay it is the final step, which is not required. What you have done so far is correct for this type of step. It is unclear what the HMM-CLUST is requiring - clustered with the other matches/steps? The idea was that we would treat these differently on the different molecules (PROTEIN/DNA).  At the moment, we are not capture that in the DESC file.

**Comment by LornaMGnify** [comment]
It seems for HMM-CLUST steps, they should be within 3000bp of any/all (?) HMM steps in pathway. Do you want me to add this kind of info about how the properties are calculated to the DESC file?

**Comment by rdfinn** [comment]
Is that a standard distance, or is that defined for each property? If it is specific, then we do need to capture this info.

**Comment by LornaMGnify** [comment]
It is a standard distance, specified in the release notes. So for HMM-CLUST it seems this will always be the value.

**Comment by almitchell** [comment]
According to the paper, it is standard:

**Comment by almitchell** [comment]
Genome Properties allows an evidence type designated HMM-CLUST, meaning that a protein must be a member of the designated protein family but also within 3000 base pairs of another marker of the same system.

**Comment by rdfinn** [comment]
Okay - so we need to capture those steps which are cluster based. I guess this is different to GP0040, where the clustering needs to be within one ORF.  But in this case does step 3 apply to step 1 or step 2 or both?

**Comment by LornaMGnify** [comment]
Agreed that GenProp0040 is a different case as there are specifics about the distances involved there (was going to add that to this conversation but didn't want to get off-topic). there are other cases like GP40.
For the basic HMM-CLUST cases like this, it looks from Alex's quote from paper that it only has to be within 3000bp of another HMM from property - I take that to mean 1 other, as opposed to all others.

**Comment by rdfinn** [comment]
I would go through some more GP and see how many different variations on the clustering we find. This comes back to the various strands of thinking during the curation process.

**Comment by LornaMGnify** [comment]
agreed - will continue to make issues labeled "hmm-clust" and "needs calculation" as required, to flag them up as I go.

**Comment by LornaMGnify** [comment]
moved to curation comment
