### ISSUE TITLE
GenProp0045 - Is there an OR function in calculating steps?

### ISSUE THREAD

**Issue by LornaMGnify** [ebi-pf-team/genome-properties#12]
I am concerned that this property might never (or rarely) resolve to a yes as it looks like two of the steps seem to be describing alternate routes through the pathway. Are OR's ever included in the property calculations?

**Comment by rdfinn** [comment]
No concept of an OR.

**Comment by rdfinn** [comment]
I can not see these enzymes on the pathway map......

**Comment by rdfinn** [comment]
I think this is more appropriate map. map00400.  As you said, it appears this pathway is showing multiple routes to tyrosine biosynthesis.

**Comment by LornaMGnify** [comment]
edited to describe just one path
