### ISSUE TITLE
Enzyme Nomenclature accepted names?

### ISSUE THREAD

**Issue by ndrawlings** [ebi-pf-team/genome-properties#15]
Should we be changing existing enzyme names to the Accepted Names from Enzyme Nomenclature (I notice that these used to be "Recommended Names")?  If we should change them, then do we change ID or DN lines, or both?

**Comment by rdfinn** [comment]
The ID and DN are somewhat redundant. The DN is the name the sequences should inherit. In theory, we should probably try and be consistent with UniProt/Swiss-Prot when choosing names. You should update both ID and DN to be consistent.
