### ISSUE TITLE
GenProp0155 and hydrogensulfite reductase

### ISSUE THREAD

**Issue by ndrawlings** [ebi-pf-team/genome-properties#16]
GenProp0155 has hydrogensulfite reductase listed as an enzyme.  This used to be EC 1.8.99.3 but has been deleted with the comment: "now known to be an in vitro artifact of EC 1.8.99.5, dissimilatory sulfite reductase".  If this activity is an artefact, then surely it can't be part of a Genome Property?

**Comment by rdfinn** [comment]
Is this just not that the activity of the enzyme is mislabelled?
