### ISSUE TITLE
GenProp2003

### ISSUE THREAD

**Issue by LornaMGnify** [ebi-pf-team/genome-properties#22]
4 steps listed unintegrated panthers. I have integrated 3 of these, but for SN1 I have replaced the evidence with a PIRSF model that was already integrated - IPR014394. This model is slightly more specific than the suggested unintegrated panther. However, the model also hits the homologous protein hepatocyte growth factor activator. Is this OK?

**Comment by ndrawlings** [comment]
No, not really.  Hepatocyte growth factor activator has nothing to do with blood coagulation.

**Comment by LornaMGnify** [comment]
Yeah I know it doesn't, but they are in the same family by homology, and all available models hit them both so presumably they cannot be (easily) separated out. I was wondering if we should just reflect this is the threshold value - e.g. raise it by 1 to cover for the fact that this step may overhit.

**Comment by ndrawlings** [comment]
The sequences differ in their first 80 residues, so separating them should be relatively trivial.  These represent a gene duplication present in all tetrapods, probably all vertebrates, so should be separate entities in Panther.
