### ISSUE TITLE
GenProp0046 and GenProp0836 have SNs with words instead of letters.

### ISSUE THREAD

**Issue by LeeBergstrand** [ebi-pf-team/genome-properties#31]
GenProp0046 and GenProp0836 have SNs with words instead of letters. Is there a specific reason for this? The [docs](http://genome-properties.readthedocs.io/en/latest/flatfile.html#desc-file) indicate that ```SN``` stands for  ```Step number```. Should SN for these records be ```1```?

From GenProp0046:

```
SN  IPP
ID  IPP biosynthesis
RQ  1
EV  GenProp0047;
TG  GO:0009240;
EV  GenProp0048;
TG  GO:0009240;
```

From GenProp0836:
```
SN  menaquin
ID  Menaquinone biosynthesis: SEPHCHC or futalosine
RQ  1
EV  GenProp0058;
EV  GenProp0829;
```

Interestingly, both are ```METAPATH``` with only one step. However, ```GenProp0199``` is also a ```METAPATH``` with only one step and it follows the number convention.

From GenProp0199:
```
SN  1
ID  Lysine biosynthesis pathways
RQ  1
EV  GenProp0125;
EV  GenProp0193;
EV  GenProp0788;
```

**Comment by LornaMGnify** [comment]
As part of the process of preparing this data for integration into InterPro and presenting it in the new viewer, we are converting the SN's from strings to numbers. This is an ongoing process, these two properties (along with others) simply hadn't been converted yet. This github repo is really a working area.
We are hoping to make a release fairly soon. This release will contain all the properties which are ready to be made public at this point.

**Comment by LeeBergstrand** [comment]
@happy-lorna Understood. Thanks!
