### ISSUE TITLE
interpro cross-talk

### ISSUE THREAD

**Issue by LornaMGnify** [ebi-pf-team/genome-properties#35]
- [ ] check that the interpro csv file is being used to validate every member DB and InterPro accession

- [ ] capture the member dbs used in GPs and propagate to InterProScan searches

**Comment by LeeBergstrand** [comment]
@happy-lorna I have bash script for this.


### Databases used for all genome properties:
```shell
find . -name 'DESC' | parallel cat {} | egrep "^EV" | egrep -oh '[a-zA-Z]+[0-9]+;' | grep -v 'IPR' | grep -v 'GenProp' | egrep -v '^SF' | sed -E 's/[0-9]+;//' | sort | uniq
```

#### Gives:

| Prefix    | Database |
|-------	|------------------------------------------------------------------------	|
| PD    	| ProDOM                                                                 	|
| PF    	| PFAM                                                                   	|
| PIRSF 	| PIRSF                                                                  	|
| PR    	| PRINTS                                                                 	|
| PS    	| PROSITE                                                                	|
| PTHR  	| PANTHER                                                                	|
| SM    	| SMART                                                                  	|
| TIGR  	| TIGRFAM                                                                	|
| cd    	| Conserved Domain Database                                              	|
| d     	| This is a mistake in GenProp2057 Step 7. EV d08045; should be cd08045; 	|


### Databases used for released genome properties:

```shell
cat ./flatfiles/genomeProperties.txt | egrep "^EV" | egrep -oh '[a-zA-Z]+[0-9]+;' | grep -v 'IPR' | grep -v 'GenProp' | egrep -v '^SF' | sed -E 's/[0-9]+;//' | sort | uniq
```

#### Gives:

| Prefix    | Database |
|-------	|------------------------------------------------------------------------	|
| PF    	| PFAM                                                                   	|
| PIRSF 	| PIRSF                                                                  	|
| PTHR  	| PANTHER                                                                	|
| SM    	| SMART                                                                  	|
| TIGR  	| TIGRFAM                                                                	|
| cd    	| Conserved Domain Database                                              	|

**Comment by LornaMGnify** [comment]
Hi Lee,
I'm sorry not to have responded sooner, your comment here slipped under my radar I'm afraid. Thanks for sending the bash scripts though. 
I had been using the "issues" to keep track of tasks between myself and my colleagues (which wasn't ideal) so I am clearing them out a bit now.
Lorna.
