### ISSUE TITLE
GenProp0014 - devoid of steps - requires calculation

### ISSUE THREAD

**Issue by rdfinn** [ebi-pf-team/genome-properties#4]
Looks like there are steps/families that one could use. There is a comment that can be delete - "Allowed states:  YES  NO".  This should be achieved by the evaluation threshold.  There seems to be a lot on the evaluation of this method.  Certainly move these to private comments.

Can you find an InterPro entry that matches all of those domains in a single domain architecture?

This may also need a length condition. We need to probably put this in a pile of those that need a special condition....

**Comment by LornaMGnify** [comment]
I think IPR004432 (TIGR02813) seems to overlap all the Pfams listed (not thioesterase PF00975 - although this is not listed as one of the minimum set of domains for production of a polyketide chain.)

**Comment by LornaMGnify** [comment]
We still need a distance constraint for this so I have not added the HMM as evidence.

**Comment by LornaMGnify** [comment]
moved to curation comment
