### ISSUE TITLE
GenProp0016 - requires calculation

### ISSUE THREAD

**Issue by rdfinn** [ebi-pf-team/genome-properties#5]
SN  4
ID  selenocysteine-specific tRNA (tRNA-SeC)
DN  NOT APPLICABLE
RQ  1

The above is going to be impossible for us to calculate, unless we have DNA.  I think that we should either delete this step, or set RQ to be required. We may also need to indicate the biological entity that the step can be calculated against?

Additionally - step one could be tested for, but using a non-hmm approach. 

Discuss.....

**Comment by LornaMGnify** [comment]
I removed the incalculable steps (deleted SN 1 and commented out SN 4 for now).
We still need to measure for tRNA. This calculation will need to be added before this is ready.

**Comment by LornaMGnify** [comment]
moved to curation comment
