### ISSUE TITLE
GenProp0021 - fix comment

### ISSUE THREAD

**Issue by rdfinn** [ebi-pf-team/genome-properties#6]
CC  ........We (Haft, et al.) described
CC  subtypes in which certain groups of subtype-specific genes are found in
CC  addition to characteristic sets of the more widely distributed cas
CC  genes [2].

Is it the paper that describes these sub-types or is this unpublished. I no not like the use of 'We', Haft et al.

**Comment by LornaMGnify** [comment]
paper describes them. I have reworked the CC lines.
