### ISSUE TITLE
GenProp0030 - Sufficient?

### ISSUE THREAD

**Issue by rdfinn** [ebi-pf-team/genome-properties#9]
Can not work out why TIGR01435 is not sufficient. This is a gene fusion of gshA and gshB.....These are represented individual as other models.

**Comment by LornaMGnify** [comment]
From the function it says it is glutamate--cysteine ligase/glutathione synthase - however, from the annotation it looks like it is glutamate--cysteine ligase/cyanophycin synthetase (and no glutathione synthase is indicated in the InterPro domain architecture). This does not explain why it is not set to sufficient for step 1 (glutamate--cysteine ligase) however!

**Comment by LornaMGnify** [comment]
removed TIGR01435 as SN2 evidence, as does not seem to demonstrate glutathione synthase function.
